[package]
name = "revello"
version = "0.1.0"
edition = "2021"

[lib]
name = "revello"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
macroquad = "0.4"
tokio = { version = "1", features = ["full"] }
